CREATE DATABASE db_landing_page;
USE db_landing_page;
CREATE TABLE contactanos
(
NOMCON VARCHAR(80),
CORRCON VARCHAR(80),
ASUCON VARCHAR(80),
DESCON VARCHAR(80)
);

SELECT
NOMCON AS NOMBRES,
CORRCON AS GMAIL,
ASUCON AS ASUNTO,
DESCON AS DESCRIPCIÓN
FROM contactanos;

ALTER TABLE contactanos
ADD CONSTRAINT NOMBRE_NOBLANCO CHECK(LENGTH(NOMCON)> 1),
ADD CONSTRAINT GMAIL_noBLANCO CHECK(LENGTH(CORRCON)> 1),
ADD CONSTRAINT ASUNTO_SINBLANCO CHECK(LENGTH(ASUCON)> 1),
ADD CONSTRAINT DESCRIPCIÓN_sinBLANCO CHECK(LENGTH(DESCON)> 1);
drop table contactanos;
select * from contactanos; 